### ISSUE TITLE
Issues with setting the Site Default image from asset

### ISSUE THREAD

**Issue by sg-modlab** [statamic/seo-pro#103] opened 2020-08-14 02:02 UTC
v3.0.0-beta.43

I defined my container in config and  now have option to select custom and browse from my assets. I select a png and save and it seems to save. 

<img width="712" alt="image" src="https://user-images.githubusercontent.com/529067/90203957-1e445a00-ddb0-11ea-9409-6cdf13eff593.png">

Then when I navigate away and then return the image is no longer shown.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/529067/90204088-3e741900-ddb0-11ea-947d-8ab2f5015b9f.png">

Finally when an image is selected I am now getting the following error on all my pages.

https://flareapp.io/share/pPvbO1Py#F1

**Comment by jesseleite** [comment] 2020-08-14 18:23
Fixed in 2.0.5 (will tag soon).

**Comment by mikemartin** [comment] 2020-08-16 02:44
@jesseleite Thanks for all your help with this. I seem to be experiencing this same issue with an entry's Social image.
<img width="672" alt="Screen Shot 2020-08-16 at 12 40 12 pm" src="https://user-images.githubusercontent.com/414211/90325373-283ba800-dfbe-11ea-8cef-942727af4669.png">

**Comment by jesseleite** [comment] 2020-09-15 20:48
I believe this is fixed in the latest update, and cannot reproduce.  Let us know if you're still experiencing an issue!

**Closed by jesseleite** 2020-09-15 20:48 UTC
