### ISSUE TITLE
Blade meta tag fails to display unique content

### ISSUE THREAD

**Issue by jolora** [statamic/seo-pro#228] opened 2022-07-21 10:53 UTC
I have a simple(ish) site with around 100 entries and only 2 collections in local development. I've just installed SEO Pro and used the `@seo_pro('meta')` blade tag (I'm using Blade throughout) in my main layout file.

Although the previews of meta data in the control panel look good, the output on the frontend is always the same. For example, the meta <title> is always "Home | Site Name"... even if I add a custom title to an entry in the control panel.

Possibly unrelated but reports will not generate either. The progress timer continues to count but the percentage never increases from 0%... my laravel.log shows no errors, nor does my browser console. *UPDATE: Just ran `seo-pro:generate-report` via command line and that generated a report fine in just a few seconds. So its just the control panel UI that fails to generate reports.*

I've cleared all caches but that's not helped.

Any ideas please?

Running Statamic 3.3.22 and SEO Pro 3.1.0 on PHP 8.1.2

**Comment by jolora** [comment] 2022-07-21 11:24
Looks like this is related to #224 ... maybe not exactly a bug in SEO Pro but as the majority will use a layout component for the <head> I think it's fair to say that the blade directive doesn't work as expected.

**Comment by jesseleite** [comment] 2022-07-26 17:18
Yeah layout components are becoming more common. We'll be looking into it for sure, but closing this issue as it's a duplicate of #224 👍

**Closed by jesseleite** 2022-07-26 17:18 UTC

**Comment by jesseleite** [comment] 2022-11-07 23:52
Should be fixed in 3.1.1 🤘
