### ISSUE TITLE
Site defaults not localizable?

### ISSUE THREAD

**Issue by wautersj** [statamic/seo-pro#341] opened 2024-07-18 08:32 UTC
I filled in the site default SEO description for my "root site".

Then switched to the "german site" with the site selector in the top right.

I saved the german site default SEO description.

I switched back to my root site; and now see the german description there too.

Is there no way to set the description per site? I would find it most logically that this would be possible.

Or maybe i'm doing it wrong? 

Would appreciate advice or support!

<img width="1190" alt="Screenshot 2024-07-18 at 10 28 15" src="https://github.com/user-attachments/assets/71be76ae-6d91-4e41-8f6f-b95eec398bb4">

**Comment by jesseleite** [comment] 2024-07-18 20:21
@wautersj You aren't doing anything wrong! It's just not supported yet (but we're going to loop back to this soon as I've hacked on it a bit already).

PS. Closing this issue, as it's a duplicate of https://github.com/statamic/seo-pro/issues/289

**Closed by jesseleite** 2024-07-18 20:21 UTC
