### ISSUE TITLE
Feature Request: Complete Seo pro  plugin 

### ISSUE THREAD

**Issue by mauriciodulce** [statamic/seo-pro#17] opened 2018-08-03 03:01 UTC
Hi.
Please complete or add this features in the plugin.

- Global Metadata
- Website Identity
- Contacts
- Social profiles
- Verify Ownership
- Customization: Example Site title (- \ |) Article title or page or collection.
- Robots
- Robot.txt
- Sitemaps
- shema.org
- Dublin core.

Tks

**Comment by jackmcdade** [comment] 2018-08-03 11:00
Many of these features are already a part of SEO Pro. This list makes me think you didn't take the time to learn what it actually does, and just pasted a list of features from the web somewhere, or a spec doc. Each item itself should be a feature request (new issue) so it can be discussed and it's purpose and debated. I'll address each one though.

**Global Metadata**
This is the primary purpose of what it does. It already does it, unless you mean something different.

**Website Identity**
What does this mean?

**Contacts**
What does this mean?

**Social profiles**
What does this mean?

**Verify Ownership**
Do you mean like when Google has you add an .html file to verify a domain? That's beyond the scope of an SEO addon. Completely unrelated.

**Customization: Example Site title (- \ |) Article title or page or collection.**
Duplicate of #16.

**Robots**
Statamic already ships with a `robots.txt` file you can work with. To leave this open to fiddling in the control panel may have unwanted (really bad) consequences for someone who doesn't understand the rules. I would much prefer to keep this out.

**Robots.txt**
Isn't that the same thing?

**Sitemaps**
Already a feature

**shema.org** 
Do you mean schema.org? We've thought about it. Would need some thinking around the best way to do it in a meaningful and uncomplicated way. It was not a 1.0 feature.

**Dublin core**
We've thought about it. Would need some thinking around the best way to do it in a meaningful and uncomplicated way. It was not a 1.0 feature.

I'm closing this issue because each item must be evaluated on its own.

**Closed by jackmcdade** 2018-08-03 11:00 UTC
