### ISSUE TITLE
Pipe character doesn't work as Site Name Separator without single or double quotes

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/seo-pro#46] opened 2018-10-25 17:36 UTC
Entering `|` as the separator in the CP saves in the seo_pro.yaml file as 
`site_name_separator: | `which doesn't conform with yaml formatting. You have to manually enter `'|'` or `"|"` in seo_pro.yaml in addon settings to get it to work.

**Comment by jasonvarga** [comment] 2018-10-25 17:36
Duplicate of https://github.com/statamic/seo-pro/issues/37

**Closed by jasonvarga** 2018-10-25 17:36 UTC
