### ISSUE TITLE
Bug: hreflang default must be present as well

### ISSUE THREAD

**Issue by kodeine** [statamic/seo-pro#44] opened 2018-10-17 19:04 UTC
as the title says, default hreflang tag should be present along with the other languages.

**Comment by pmeissner** [comment] 2018-12-03 18:33
```hreflang="x-default"``` should be in there, and I believe the page should include a reference to itself. Currently seo-pro looks like it only outputs the alternates of the other available languages. ref: [Moz](https://moz.com/learn/seo/hreflang-tag)

**Comment by pmeissner** [comment] 2018-12-03 18:58
Sorry, my comment may be a dupe of this: [https://github.com/statamic/seo-pro/issues/49](issue 49)

**Comment by jackmcdade** [comment] 2019-06-27 16:01
👍 Closing as duplicate.

**Closed by jackmcdade** 2019-06-27 16:01 UTC

**Comment by clementmas** [comment] 2025-03-07 15:35
This is not a duplicate. The other issue doesn't mention the missing `x-default` tag.

I would have expected SEO Pro to handle this. Instead, I have to add this to my layouts:

```antlers
{{ seo_pro:meta }}

{{ locales:en }}
    <link rel="alternate" href="{{ permalink }}" hreflang="x-default" />
{{ /locales:en }}
```

There should be a `default` option in the sites config or the first one should be picked as the `x-default`.

**Comment by duncanmcclean** [comment] 2025-03-07 15:53
This issue has been closed for over 4.5 years and was regarding an older version of SEO Pro. If this is still an issue for you, please open a new issue.
