### ISSUE TITLE
Can't remove SEO section from collection

### ISSUE THREAD

**Issue by edalzell** [statamic/seo-pro#102] opened 2020-08-13 00:01 UTC
How does one remove the SEO section from a collection? I tried `seo: false` in the collection's yaml but the section still showed up.

This is Statamic v2

**Comment by jesseleite** [comment] 2020-08-13 00:02
This is solved in SEO Pro for v3.

**Comment by jesseleite** [comment] 2020-08-14 18:26
Going to close this for now.  It's technically not a bug, but a UX improvement we made in v3.  Given that we're not actively improving SEO Pro for v2, I'd just recommend upgrading to v3 at this point.

**Closed by jesseleite** 2020-08-14 18:26 UTC

**Comment by stuartcusackie** [comment] 2022-02-09 12:25
Does this be re-opened? I am trying: `seo: false` in my collection's YAML but the panel keeps coming back.

On Statamic v3 and SEO Pro 2.3.2
