### ISSUE TITLE
Permission denied and "wrong" labels/titles

### ISSUE THREAD

**Issue by philipboomy** [statamic/seo-pro#81] opened 2020-01-19 08:26 UTC
For some reason I am seeing wrong labels/titles on this site. Used SEO Pro many times before without issues though this is my first multi locale site with SEO Pro.

https://share.getcloudapp.com/P8uYDXbv

The worst though is the cp.setting in the sidebar menu. If client clicks on it with his "non-super" role he gets a permission denied error. For me with super admin I can see the settings just fine.

Statamic 2.11.17
SEOPro 1.3.1
Happens on Forge server (PHP 7.2) and local Valet.

**Comment by philipboomy** [comment] 2020-02-17 10:13
I am wondering if you have had a chance to look into this?

**Comment by jesseleite** [comment] 2020-09-15 18:51
A lot of this has been reworked in SEO Pro for Statamic v3.  Closing this issue, but if you are still experiencing with the latest version we can re-open!

**Comment by philipboomy** [comment] 2020-09-16 09:12
That took a while to get a response here and then it does not seem to help me. This client is on V2 and no budget for upgrade to V3 especially since he was told it was free (as that what was I was told first). Any chance you can fix it for V2 too?

**Comment by jesseleite** [comment] 2020-09-16 21:35
Hey Philip, I apologize for the delay in addressing this issue. As you know, we're very focused on all things v3 going forward. As for the client having no budget, we totally empathize with that. This is why we offer free v3 Pro license upgrades for v2 licenses purchased since 2019 (or $59 for anything older). That said, I've re-opened the issue 👍 

![image](https://user-images.githubusercontent.com/5187394/93390912-6f76bc00-f83c-11ea-9c3d-dacc350f9c28.png)

I just pushed a fix for that menu item and permission denied error.  Addon settings pages are meant to be accessed by super users only, so showing this page for non-super users was an oversight.

![image](https://user-images.githubusercontent.com/5187394/93390931-769dca00-f83c-11ea-835d-04c15bbf0e0c.png)

As for that button, I can't reproduce what you're seeing there.  Do you still see this with Statamic 2.11.20 and SEO Pro 1.3.3?

**Comment by jesseleite** [comment] 2021-09-18 17:46
Closing due to inactivity. feel free to squawk if you would like to re-open this!

**Closed by jesseleite** 2021-09-18 17:46 UTC
Labels: statamic v2
